default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  username: naw4t

development:
  <<: *default
  database: virgo4_pda_development

test:
  <<: *default
  database: virgo4_pda_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
