default: &default
  adapter: postgresql
  #encoding: unicode
  pool: 5
  encoding: utf8
  host:     <%= ENV['DBHOST'] %>
  port:     <%= ENV['DBPORT'] %>
  database: <%= ENV['DBNAME'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
