default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  username: naw4t

development:
  <<: *default
  database: virgo4_pda_development

test:
  <<: *default
  database: virgo4_pda_test

